#include <string>

#define PROPERTY_CMD_CHANGE_CAMERA_PARAMS "cmds/reloadCameraParams"
#define PROPERTY_CMD_FORCE_CHANGE "cmds/forceReload"

#define CAMERA_TOP_PREFIX "params/cameraTop"
#define CAMERA_BOTTOM_PREFIX "params/cameraBottom"

#define PROPERTY_SUFFIX_Brightness "Brightness"
#define PROPERTY_SUFFIX_Contrast "Contrast"
#define PROPERTY_SUFFIX_Saturation "Saturation"
#define PROPERTY_SUFFIX_Hue "Hue"
#define PROPERTY_SUFFIX_RedChroma "RedChroma"
#define PROPERTY_SUFFIX_BlueChroma "BlueChroma"
#define PROPERTY_SUFFIX_Gain "Gain"
#define PROPERTY_SUFFIX_HFlip "HFlip"
#define PROPERTY_SUFFIX_VFlip "VFlip"
#define PROPERTY_SUFFIX_LensX "LensX"
#define PROPERTY_SUFFIX_LensY "LensY"
#define PROPERTY_SUFFIX_AutoExposition "AutoExposition"
#define PROPERTY_SUFFIX_AutoWhiteBalance "AutoWhiteBalance"
#define PROPERTY_SUFFIX_AutoGain "AutoGain"
#define PROPERTY_SUFFIX_Exposure "Exposure"
#define PROPERTY_SUFFIX_ExposureCorrection "ExposureCorrection"


#define PROPERTY_PARAMS_CAMERA_TOP_Brightness  CAMERA_TOP_PREFIX"/"PROPERTY_SUFFIX_Brightness
#define PROPERTY_PARAMS_CAMERA_BOTTOM_Brightness  CAMERA_BOTTOM_PREFIX"/"PROPERTY_SUFFIX_Brightness
#define PROPERTY_PARAMS_CAMERA_TOP_Contrast  CAMERA_TOP_PREFIX"/"PROPERTY_SUFFIX_Contrast
#define PROPERTY_PARAMS_CAMERA_BOTTOM_Contrast  CAMERA_BOTTOM_PREFIX"/"PROPERTY_SUFFIX_Contrast
#define PROPERTY_PARAMS_CAMERA_TOP_Saturation  CAMERA_TOP_PREFIX"/"PROPERTY_SUFFIX_Saturation
#define PROPERTY_PARAMS_CAMERA_BOTTOM_Saturation  CAMERA_BOTTOM_PREFIX"/"PROPERTY_SUFFIX_Saturation
#define PROPERTY_PARAMS_CAMERA_TOP_Hue  CAMERA_TOP_PREFIX"/"PROPERTY_SUFFIX_Hue
#define PROPERTY_PARAMS_CAMERA_BOTTOM_Hue  CAMERA_BOTTOM_PREFIX"/"PROPERTY_SUFFIX_Hue
#define PROPERTY_PARAMS_CAMERA_TOP_RedChroma  CAMERA_TOP_PREFIX"/"PROPERTY_SUFFIX_RedChroma
#define PROPERTY_PARAMS_CAMERA_BOTTOM_RedChroma  CAMERA_BOTTOM_PREFIX"/"PROPERTY_SUFFIX_RedChroma
#define PROPERTY_PARAMS_CAMERA_TOP_BlueChroma  CAMERA_TOP_PREFIX"/"PROPERTY_SUFFIX_BlueChroma
#define PROPERTY_PARAMS_CAMERA_BOTTOM_BlueChroma  CAMERA_BOTTOM_PREFIX"/"PROPERTY_SUFFIX_BlueChroma
#define PROPERTY_PARAMS_CAMERA_TOP_Gain  CAMERA_TOP_PREFIX"/"PROPERTY_SUFFIX_Gain
#define PROPERTY_PARAMS_CAMERA_BOTTOM_Gain  CAMERA_BOTTOM_PREFIX"/"PROPERTY_SUFFIX_Gain
#define PROPERTY_PARAMS_CAMERA_TOP_HFlip  CAMERA_TOP_PREFIX"/"PROPERTY_SUFFIX_HFlip
#define PROPERTY_PARAMS_CAMERA_BOTTOM_HFlip  CAMERA_BOTTOM_PREFIX"/"PROPERTY_SUFFIX_HFlip
#define PROPERTY_PARAMS_CAMERA_TOP_VFlip  CAMERA_TOP_PREFIX"/"PROPERTY_SUFFIX_VFlip
#define PROPERTY_PARAMS_CAMERA_BOTTOM_VFlip  CAMERA_BOTTOM_PREFIX"/"PROPERTY_SUFFIX_VFlip
#define PROPERTY_PARAMS_CAMERA_TOP_LensX  CAMERA_TOP_PREFIX"/"PROPERTY_SUFFIX_LensX
#define PROPERTY_PARAMS_CAMERA_BOTTOM_LensX  CAMERA_BOTTOM_PREFIX"/"PROPERTY_SUFFIX_LensX
#define PROPERTY_PARAMS_CAMERA_TOP_LensY  CAMERA_TOP_PREFIX"/"PROPERTY_SUFFIX_LensY
#define PROPERTY_PARAMS_CAMERA_BOTTOM_LensY  CAMERA_BOTTOM_PREFIX"/"PROPERTY_SUFFIX_LensY
#define PROPERTY_PARAMS_CAMERA_TOP_AutoExposition  CAMERA_TOP_PREFIX"/"PROPERTY_SUFFIX_AutoExposition
#define PROPERTY_PARAMS_CAMERA_BOTTOM_AutoExposition  CAMERA_BOTTOM_PREFIX"/"PROPERTY_SUFFIX_AutoExposition
#define PROPERTY_PARAMS_CAMERA_TOP_AutoWhiteBalance  CAMERA_TOP_PREFIX"/"PROPERTY_SUFFIX_AutoWhiteBalance
#define PROPERTY_PARAMS_CAMERA_BOTTOM_AutoWhiteBalance  CAMERA_BOTTOM_PREFIX"/"PROPERTY_SUFFIX_AutoWhiteBalance
#define PROPERTY_PARAMS_CAMERA_TOP_AutoGain  CAMERA_TOP_PREFIX"/"PROPERTY_SUFFIX_AutoGain
#define PROPERTY_PARAMS_CAMERA_BOTTOM_AutoGain  CAMERA_BOTTOM_PREFIX"/"PROPERTY_SUFFIX_AutoGain
#define PROPERTY_PARAMS_CAMERA_TOP_Exposure  CAMERA_TOP_PREFIX"/"PROPERTY_SUFFIX_Exposure
#define PROPERTY_PARAMS_CAMERA_BOTTOM_Exposure  CAMERA_BOTTOM_PREFIX"/"PROPERTY_SUFFIX_Exposure
#define PROPERTY_PARAMS_CAMERA_TOP_ExposureCorrection  CAMERA_TOP_PREFIX"/"PROPERTY_SUFFIX_ExposureCorrection
#define PROPERTY_PARAMS_CAMERA_BOTTOM_ExposureCorrection  CAMERA_BOTTOM_PREFIX"/"PROPERTY_SUFFIX_ExposureCorrection

#define PROPERTY_PARAMS_Resolution "params/resolution"
#define PROPERTY_PARAMS_Colorspace "params/colorspace"
#define PROPERTY_PARAMS_FrameRate "params/framerate"
#define PROPERTY_PARAMS_CAMERA_Select "params/cameraSelect"
#define PROPERTY_PARAMS_LINK_PARAMS "params/linkParameters"

#define PROPERTY_OUT_IMAGE "out/image"

#define PROPERTY_DBG_ENABLED "dbg/enable"
#define PROPERTY_DBG_IMAGE "dbg/smallImage"

#define PROPERTY_OUT_JOINTS "out/joints"
#define PROPERTY_OUT_SENSORS      "out/sensors"
#define PROPERTY_OUT_BATTERY      "out/batteryCharge"
#define PROPERTY_OUT_SENSORS_TIMESTAMP	  "out/sensorsTimestamp"
#define PROPERTY_OUT_ALLDATA	  "out/alldata"
#define PROPERTY_OUT_POSE	  "out/pose"
#define PROPERTY_PARAMS_PERIOD "params/period"
#define PROPERTY_DEBUG_ENABLED "dbg/enabled"

