#define PROPERTY_CMD_CONNECT "cmds/connect"
#define PROPERTY_CMD_CHANGE_CAMERA_PARAMS "cmds/reloadCameraParams"

#define PROPERTY_PARAMS_CONNECT_PARENT_BROKER "params/connection/parentBroker"
#define PROPERTY_PARAMS_CONNECT_PARENT_BROKER_PORT "params/connection/parentBrokerPort"
#define PROPERTY_PARAMS_CONNECT_BROKER "params/connection/broker"
#define PROPERTY_PARAMS_CONNECT_BROKER_PORT "params/connection/brokerPort"

#define PROPERTY_PARAMS_CAMERA_Brightness "params/camera/Brightness"
#define PROPERTY_PARAMS_CAMERA_Contrast "params/camera/Contrast"
#define PROPERTY_PARAMS_CAMERA_Saturation "params/camera/Saturation"
#define PROPERTY_PARAMS_CAMERA_Hue "params/camera/Hue"
#define PROPERTY_PARAMS_CAMERA_RedChroma "params/camera/RedChroma"
#define PROPERTY_PARAMS_CAMERA_BlueChroma "params/camera/BlueChroma"
#define PROPERTY_PARAMS_CAMERA_Gain "params/camera/Gain"
#define PROPERTY_PARAMS_CAMERA_HFlip "params/camera/HFlip"
#define PROPERTY_PARAMS_CAMERA_VFlip "params/camera/VFlip"
#define PROPERTY_PARAMS_CAMERA_LensX "params/camera/LensX"
#define PROPERTY_PARAMS_CAMERA_LensY "params/camera/LensY"
#define PROPERTY_PARAMS_CAMERA_AutoExposition "params/camera/AutoExposition"
#define PROPERTY_PARAMS_CAMERA_AutoWhiteBalance "params/camera/AutoWhiteBalance"
#define PROPERTY_PARAMS_CAMERA_AutoGain "params/camera/AutoGain"
#define PROPERTY_PARAMS_CAMERA_Exposure "params/camera/Exposure"
#define PROPERTY_PARAMS_CAMERA_ExposureCorrection "params/camera/ExposureCorrection"
#define PROPERTY_PARAMS_Resolution "params/resolution"
#define PROPERTY_PARAMS_Colorspace "params/colorspace"
#define PROPERTY_PARAMS_FrameRate "params/framerate"

#define PROPERTY_PARAMS_CAMERA_Select "params/camera/Select"

#define PROPERTY_OUT_IMAGE "out/image"
#define PROPERTY_OUT_CAMERAMATRIX "out/cameraMatrix"

