#!/bin/bash
if [ -f CMakeLists.txt ]; then
	echo "The CMakeLists.txt file already exists, please remove it by hand if you want to run this script."
else
	echo "Generating CMakeLists.txt for RAgent module."
	cat >CMakeLists.txt <<EOF
# This file has been generated by `basename $0`
RDK_ADD_RAGENT_MODULE(ALL_FILES)

# If you do not need external libraries, delete this line and those below.
# On the contrary, if you need an hypotethical PALTALIB, put an IF(PALTALIB_FOUND)/ENDIF(PALTALIB_FOUND)
# (without curly brackets) to make the module compile only if the PALTALIB has been found by
# the build system; also the macro above RDK_ADD_RAGENT_MODULE, have to be put inside the IF/ENDIF
# and can be followed by:
# INCLUDE_DIRECTORIES(\${PALTALIB_INCLUDE_DIR}) # if you need the header files of PALTALIB
# LINK_DIRECTORIES(\${PALTALIB_LINK_DIRECTORIES}) # if you need some link dir
# TARGET_LINK_LIBRARIES(\${RDK_THIS_MODULE_NAME} \${PALTALIB_LIBRARIES}) # if PALTALIB has library that have to be linked
# usually, putting all the three lines above is a safe choice; the ENDIF(PALTALIB_FOUND) should go after everything
EOF
fi

