#!/bin/bash
if [ -f CMakeLists.txt ]; then
	echo "The CMakeLists.txt file already exists, please remove it by hand if you want to run this script."
else
	echo "Generating CMakeLists.txt for subdirectory recursion."
	cat >CMakeLists.txt <<EOF

# This file has been generated by `basename $0`
RDK_ADD_ALL_SUBDIRECTORIES()
EOF
fi

